routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MainController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [MainController::class, 'index'])->name('index');

Route::get('/search', [MainController::class, 'search'])->name('search');

Route::get('/book_{id}', [MainController::class, 'detail'])->name('detail')->whereNumber('id');

Route::get('/user/mypage', function () {
    return view('motoyabooks.user.mypage');
})->middleware(['auth'])->name('mypage');

require __DIR__.'/auth.php';

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Carbon\Carbon;

class Book extends Model
{
    use HasFactory;

    public function reviews()
    {
        return $this->hasMany(Review::class);
    }

    public function getShortTitleAttribute()
    {
        return Str::limit($this->title, 40);
    }

    public function getPriceAttribute($value)
    {
        return number_format($value);
    }

    public function getPublishedAtAttribute($value)
    {
        return Carbon::parse($value)->format("Y/m/d");
    }

    public function getReviewsCountAttribute()
    {
        return $this->reviews->count();
    }

    public function getReviewsAverageAttribute()
    {
        $review_average = $this->reviews->avg('score');
        $rounded_score = floor($review_average * 2) / 2;
        return $rounded_score;
    }

    public function getRecentReviewsAttribute()
    {
        return $this->reviews->take(3);
    }

    public function getOtherReviewsAttribute()
    {
        return $this->reviews->skip(3);
    }
}

app/Models/Review.php
<?php

namespace App\Models;
use Carbon\Carbon;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Review extends Model
{
    use HasFactory;

    public function book()
    {
        return $this->belongsTo(Book::class);
    }

    public function getPostedAtAttribute($value)
    {
        return Carbon::parse($value)->format("Y/m/d");
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MainController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Book;
use App\Models\Review;

class MainController extends Controller
{
    public function index()
    {
        $books = Book::with('reviews')->orderByDesc('published_at', 'desc')->get();

        return view('motoyabooks.index', compact('books'));
    }

    public function search(Request $request)
    {
        $keyword = $request->input('keyword');
        $query = Book::with('reviews');

        if ($request->filled('keyword')) {
            $query->where('title', 'LIKE', "%{$keyword}%")
                ->orWhere('description', 'LIKE', "%{$keyword}%");
        }

        $books = $query->paginate(30);

        return view('motoyabooks.search', compact('books', 'keyword'));
    }

    public function detail(Request $request, $id)
    {
        $book = Book::findOrFail($id);

        return view('motoyabooks.detail', compact('book'));
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
    public function mypage()
    {
        return view('motoyabooks.user.mypage');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('motoyabooks.components.common');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">
        <link rel="stylesheet" href="{{ asset('css/main.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body id="{{ $id }}">
        {{ $header }}
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="flex items-center px-4">
                <div class="flex-shrink-0">
                    <svg class="h-10 w-10 fill-current text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                    </svg>
                </div>

                <div class="ml-3">
                    <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                    <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
                </div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>

resources/views/motoyabooks/components/common.blade.php
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{{ asset('css/main.css') }}">
  <title>MotoyaBooks</title>
</head>
<body id="@yield('id')">
  @yield('header')
  <div id="wrap">
    <div class="main">
      <div class="content">
          @yield('content')
      </div>
      @yield('sidebar')
    </div>
  </div>
</body>
</html>

resources/views/motoyabooks/components/header.blade.php
@section('header')
  <x-header />
@endsection

resources/views/motoyabooks/components/sidebar.blade.php
@section('sidebar')
  <aside id="sidebar">
    <section class="publish-date">
      <div class="option">発売日</div>
      <ul>
        <li><a href="">近日30日以内</a></li>
        <li><a href="">近日7日以内</a></li>
        <li><a href="">本日</a></li>
        <li><a href="">過去7日以内</a></li>
        <li><a href="">過去30日以内</a></li>
      </ul>
    </section>
    <section class="junre">
      <div class="option">ジャンル</div>
      <ul>
        <li><a href="">ビジネス書</a></li>
        <li><a href="">小説</a></li>
        <li><a href="">漫画</a></li>
        <li><a href="">雑誌</a></li>
        <li><a href="">専門書</a></li>
      </ul>
    </section>
    <section class="price-range">
      <div class="option">価格帯</div>
      <ul>
        <li><a href="">0〜1,000円</a></li>
        <li><a href="">1,000〜2,000円</a></li>
        <li><a href="">2,000〜3,000円</a></li>
        <li><a href="">3,000〜5,000円</a></li>
        <li><a href="">5,000円〜</a></li>
      </ul>
    </section>
  </aside>
@endsection

resources/views/motoyabooks/components/user_common.blade.php
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{{ asset('css/app.css') }}">
  <link rel="stylesheet" href="{{ asset('css/main.css') }}">
  <script src="{{ asset('js/app.js') }}" defer></script>
  <title>MotoyaBooks</title>
</head>
<body id="@yield('id')" class="user-layout">
  @yield('header')
  <div id="wrap">
    <div class="main">
      @yield('content')
    </div>
  </div>
</body>
</html>

resources/views/motoyabooks/components/user_header.blade.php
@section('header')
  <header>
    <nav class="global-nav">
      <div class="nav-left">
        <div class="logo">MotoyaBooks</div>
      </div>
      <div class="nav-center">
        <form action="{{ route('search') }}" method="GET" class="search-form">
          <input type="search" value="" placeholder="検索" name="keyword" class="search-form__search-box">
          <button type="submit" class="search-form__search-button">
            <img src="{{ asset('img/icon-search.svg') }}" alt="" class="search-form__search-icon">
          </button>
        </form>
      </div>
      <div class="nav-right">
        <ul class="usermenu-list">
          <li class="usermenu-list__element">
            <a class="usermenu-list__link" href="">ログイン</a>
          </li>
          <li class="usermenu-list__element">
            <a class="usermenu-list__link" href="">会員登録</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
@endsection

resources/views/motoyabooks/detail.blade.php
@extends('motoyabooks.components.common')

@section('id', 'detail')

@include('motoyabooks.components.header', ['keyword' => $keyword ?? ''])

@section('content')
  <section class="book-detail">
    <div class="book-detail__left-area">
      <img src="{{ asset('img/books/book_sasshi1.png') }}" alt="" class="book-detail__feature">
    </div>
    <div class="book-detail__right-area">
      <div class="book-detail__title">{{ $book->title }}</div>
      <div class="book-detail__published-at">{{ $book->published_at }}</div>
      <span class="book-detail__star-rating" data-rate="{{ $book->reviews_average }}"></span>
      <span class="book-detail__reviews-count">（{{ $book->reviews_count }}件のレビュー）</span>
      <div class="book-detail__price">¥ <span class="book-detail__price-num">{{ $book->price }}</span></div>
      <p class="book-detail__description">{{ $book->description }}</p>
    </div>
  </section>
  <div class="horizontal-line"></div>
  <section class="book-review">
    <ul class="review-list">
      @foreach ($book->recent_reviews as $review)
        <li class="review-list__element">
          <div class="review-list__heading">
            <span class="review-list__star-rating" data-rate="{{ $review->score }}"></span>
            <span class="review-list__title">{{ $review->title }}</span>
          </div>
          <div class="review-list__posted_at">{{ $review->posted_at }}</div>
          <p class="review-list__detail">{{ $review->detail }}</p>
        </li>
      @endforeach

      @foreach ($book->other_reviews as $review)
        <li class="review-list__element">
          <div class="review-list__heading">
            <span class="review-list__star-rating" data-rate="{{ $review->score }}"></span>
            <span class="review-list__title">{{ $review->title }}</span>
          </div>
          <div class="review-list__posted_at">{{ $review->posted_at }}</div>
          <p class="review-list__detail">{{ $review->detail }}</p>
        </li>
      @endforeach
    </ul>
  </section>
@endsection

@include('motoyabooks.components.sidebar')

resources/views/motoyabooks/index.blade.php
@extends('motoyabooks.components.common')

@section('id', 'index')

@include('motoyabooks.components.header', ['keyword' => $keyword ?? ''])

@section('content')
  <section class="popular-books">
    <h2>最近話題の本</h2>
    <ul class="book-list">
      @foreach ($books as $book)
      <li class="book-list__book">
        <a class="book-list__book_link" href="{{ route('detail', ['id' => $book->id]) }}">
          <img src="{{ asset('img/books/book_sasshi1.png') }}" alt="" class="book-list__book_feature">
          <p class="book-list__book_title">{{ $book->short_title }}</p>
          <div class="book-list__book_published_at">{{ $book->published_at }}</div>
          <span class="book-list__book_star-rating" data-rate="{{ $book->reviews_average }}"></span>
          <span class="book-list__book_reviews-count">({{ $book->reviews_count }})</span>
          <div class="book-list__book_price">¥ <span class="book-list__book_price-num">{{ $book->price }}</span></div>
        </a>
      </li>
      @endforeach
    </ul>
  </section>
@endsection

resources/views/motoyabooks/search.blade.php
@extends('motoyabooks.components.common')

@section('id', 'search')

@include('motoyabooks.components.header', ['keyword' => $keyword ?? ''])

@section('content')
  <section class="search-result">
    <div class="search-result__heading">
      <h2 class="search-result__heading_title">検索結果</h2>
      <div class="search-result__books_count">{{ $books->total() }}件のうち{{ $books->firstItem() }}〜{{ $books->lastItem() }}件目</div>
    </div>
    <ul class="book-list">
      @foreach ($books as $book)
      <li class="book-list__book">
        <a class="book-list__book_link" href="{{ route('detail', ['id' => $book->id]) }}">
          <img src="{{ asset('img/books/book_sasshi1.png') }}" alt="" class="book-list__book_feature">
          <p class="book-list__book_title">{{ $book->short_title }}</p>
          <div class="book-list__book_published_at">{{ $book->published_at }}</div>
          <span class="book-list__book_star-rating" data-rate="{{ $book->reviews_average }}"></span>
          <span class="book-list__book_reviews-count">({{ $book->reviews_count }})</span>
          <div class="book-list__book_price">¥ <span class="book-list__book_price-num">{{ $book->price }}</span></div>
        </a>
      </li>
      @endforeach
    </ul>

    {{ $books->appends(request()->input())->links('vendor.pagination.default') }}
  </section>
@endsection

@include('motoyabooks.components.sidebar')

resources/views/motoyabooks/user/mypage.blade.php
@extends('motoyabooks.components.user_common')

@section('id', 'mypage')

@include('motoyabooks.components.header')

@section('content')
  <section class="user-menu">
    <ul class="user-menu__list">
      <li class="user-menu__list_element">
        <a href="#">プロフィール</a>
      </li>
      <li class="user-menu__list_element">
        <a href="#">注文履歴の確認</a>
      </li>
      <li class="user-menu__list_element">
        <a href="#">閲覧履歴の確認・削除</a>
      </li>
      <li class="user-menu__list_element">
        <a href="#">本の確認</a>
      </li>
    </ul>
  </section>
@endsection